baseURL = "https://www.eskimo-nation.co.uk"
languageCode = "en-us"
title = "eskimo-nation.co.uk"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "articles"
name = "Articles"
url = "/articles/"
weight = 3
[[menu.main]]
identifier = "contact-us"
name = "Contact"
url = "/contact/"
weight = 2
