baseURL = "https://www.eskimo-nation.co.uk"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
languageCode = "en-us"
title = "eskimo-nation.co.uk"

[[menu.main]]
identifier = "articles"
name = "Articles"
url = "/articles/"
weight = 3
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 3
[params]
    meta_description = "DEFAULT"
    meta_keywords = "DEFAULT KEYWORDS"